### PR TITLE
feat: `--beartype-skip-packages`

### PR DESCRIPTION
**Pull request by tusharsadhwani**
This *should* work, all that's left is to actually verify if it does or not.

### CODE REVIEW

**Comment by leycec** [comment]
**Brilliant!** I rejoice to know you. This is me awkwardly saying...

> *You're amazing.*

**srsly.** I meant to give you a detailed writeup integrating this `BeartypeConf.claw_skip_package_names` black magic with the `pytest` CLI. But I guess you got there first and just reverse-engineered all of this mostly undocumented madness without me. If I had money, I'd hire you to do stuff. Lots of stuff.

Sadly, I have no money. I can only thank you. Please accept this ceremonial Canadian turkey: :turkey:

**Comment by tusharsadhwani** [comment]
I'll probably have to wait until this arg has been released on PyPI. Will it be part of 0.19?

**Comment by leycec** [comment]
**Testing!** Forgot about that. Testing is... *cumbersome.* Here's what @beartype's test suite does:

* Define a [test data module resembling this `skippable_submodule.py`](https://github.com/beartype/beartype/blob/main/beartype_test/a00_unit/data/claw/intraprocess/skippable_package/skippable_submodule.py). The following two-liner should suffice if you'd rather not bludgeon yourself over the head with the full `skippable_submodule.py`: e.g.,

```python
# Assert that a PEP 526-compliant assignment statement assigning an object
# violating the type hint annotating that statement raises *NO* exception.
this_should_fail_but_doesnt: str = b'Totally not a string, but nobody cares.'
assert isinstance(this_should_fail_but_doesnt, bytes)
```

* Skip that `skippable_submodule.py` by passing an option resembling `--beartype-skip-packages='skippable_submodule'`. Maybe? No idea.
* Pray that `tox` passes. Pray harder than you have ever prayed.

Thanks again being so awesome, @tusharsadhwani. Kali herself surely shines upon you.

**Comment by leycec** [comment]
> I'll probably have to wait until this arg has been released on PyPI. Will it be part of 0.19?

**Totally.** 0.19.0 is the plan. Alternately, users could be forced to install the live @beartype if they *really* want this. I am fine with forcing users to do stuff they don't want to do. Let them eat `git`!

Totally up to you. Thanks so much yet again. I get the sinking feeling I'd better start hacking on 0.19 *a lot* harder. :smile:

**Comment by tusharsadhwani** [comment]
You already hack at an incredible pace. There's no need to worry.

**Comment by tusharsadhwani** [comment]
oh right, i can ship this now.

**Pull request merged**
